# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_of_transaction', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.IntegerField()),
                ('to_account', models.IntegerField()),
                ('amount_transferred', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
